/*
 * generated by Xtext 2.18.0.M3
 */
package com.softtek.mxml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MxmlStandaloneSetup extends MxmlStandaloneSetupGenerated {

	def static void doSetup() {
		new MxmlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
